version: '3.8'

services:
  weaviate:
    image: semitechnologies/weaviate:1.29.11
    ports:
      - "8080:8080"
    environment:
      - QUERY_DEFAULTS_LIMIT=25
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true
      - PERSISTENCE_DATA_PATH=/var/lib/weaviate
      - DEFAULT_VECTORIZER_MODULE=none
      - ENABLE_MODULES=none
      - CLUSTER_HOSTNAME=node1
    volumes:
      - weaviate_data:/var/lib/weaviate

  app:
    build:
      context: ./app
    container_name: fastapi-app
    ports:
      - "8000:8000"
    depends_on:
      - weaviate
    volumes:
      - ./app:/app
    environment:
      - PYTHONUNBUFFERED=1
    working_dir: /app
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload

volumes:
  weaviate_data:
